import express, { Request, Response } from 'express';
import { body, validationResult } from 'express-validator';
import { User } from '../models/user';
import { RequestValidationError } from '../errors/request-validation-error';
import { BadRequestError } from '../errors/bad-request-error';
import jwt from 'jsonwebtoken'; //Importing jwt to sign the token

const router = express.Router();

router.post(
  '/api/users/signup',
  [
    body('email').isEmail().withMessage('Email must be valid'),
    body('password')
      .trim()
      .isLength({ min: 4, max: 20 })
      .withMessage('Password must be between 4 and 20 characters'),
  ],
  async (req: Request, res: Response) => {
    const errors = validationResult(req); //We use the validationResult function to get the errors from the request

    //If there are errors, we send a 400 response with the errors
    if (!errors.isEmpty()) {
      //This will be picked up by the error handler middleware
      throw new RequestValidationError(errors.array()); //We throw an error if there are errors
    }

    //After validation, we can create a new user
    //Before creating a user, we should check if the user already exists
    const { email, password } = req.body;
    const exisitingUser = await User.findOne({ email });

    if (exisitingUser) {
      throw new BadRequestError('User already exists'); //We throw an error if the user already exists
    }

    //If the user does not exist, Hash the password

    // Create a new user instance
    const user = User.build({ email, password });

    // Save the user to the database
    await user.save();

    // Respond with the user data ising JWT
    //Inside JWT, we will include the user id and email,ID generated by MongoDB to uniquely identify the user
    const userJwt = jwt.sign(
      {
        id: user.id,
        email: user.email,
      },
      'asdf'
    ); // 'asdf' is a secret key, in production use a more secure key

    // Put JWT inside the cookie session objecr
    req.session = {
      jwt: userJwt, //We set the jwt in the session
    };

    res.status(201).send(user); //201 is the status code for created
  }
);

export { router as signUpRouter };
//This is a named export, so we can import it in the index.ts file
